FROM golang:1.25-alpine

RUN apk add --no-cache git gcc musl-dev

RUN go install github.com/air-verse/air/v2@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]





